default:      &default
  adapter:    postgresql
  encoding:   unicode
  database:   bookmarks
  username:   den
  password:   <%= ENV['BOOKMARKS_DATABASE_PASSWORD'] %>
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<:         *default
  database:   bookmarks_development

test:
  <<:         *default
  database:   bookmarks_test

production:
  <<:         *default
  database:   bookmarks_production
  username:   bookmarks
  password:   <%= ENV['BOOKMARKS_DATABASE_PASSWORD'] %>
